export const users = [
  {
    id: 1,
    name: "Luis",
    location: "",
    distance: 11,
    age: 23,
    image: require("--/assets/favicon.png"),
  },
  {
    id: 2,
    name: "Jose",
    location: "",
    distance: 11,
    age: 23,
    image: require("--/assets/favicon.png"),
  },
  {
    id: 3,
    name: "Arturo",
    location: "",
    distance: 11,
    age: 23,
    image: require("--/assets/favicon.png"),
  },
  {
    id: 4,
    name: "Ramon",
    location: "",
    distance: 11,
    age: 23,
    image: require("--/assets/favicon.png"),
  },
  {
    id: 5,
    name: "Estrada",
    location: "",
    distance: 11,
    age: 23,
    image: require("--/assets/favicon.png"),
  },
];
